### PR TITLE
Trn 712 text fingerprint

### PR DESCRIPTION
**Pull request by dankinder**
The main addition here is the FnvTextFingerprint/fnv_txt field. Since we reference the data model frequently I also moved the schema into it's own file (make it easier to get a history of data model changes too).

### CODE REVIEW

**Comment by pchristopher1275** [comment]
When I look at this patch, the thing that strikes me is that there is a lot going on. A fair bit more work is here than is required to satisfy TRN-712, no? I don’t object to the refactoring per se (for example the creation of the HTMLParser class is fine AFAIC), but I guess I would have expected a separate ticket to be issued for this work (like TRN-???: refactor parse.go by creating an HTMLParser class, and moving schema into it’s own file, etc.). By doing this, a rationale for the ticket could be articulated, the ticket could be discussed among the team, and a set of complete-criterion could have been spelled out.

**Comment by cgilling** [comment]
I think it depends of the amount of work that is required. I would like to encourage some of this small cleanup stuff to be done along the way if its related and seems appropriate. I think in this case it does make it a little harder to see the changes exactly for this ticket, but I would argue that the changes aren't too large or contentious or (I think) time consuming that they would warrant a lot of discussion

**Comment by dankinder** [comment]
I'd agree with Chris. I admit the diff got a bit messy here, I'd be glad to try to issue separate pull requests or something before doing the work if the issue is reviewing the code. I tried to keep the commits neat on this one so y'all could review the individual commits pretty easily.

That said I also believe the diff is a little deceptive here regarding the quantity of work... this HTMLParser class literally is just a new name for a variety of functions that used to be free-floating or attached to the fetcher struct, plus some variables that used to be taken as arguments are now shared using that class.

I'd also say that refactoring is something that is hard to predict ahead of time but I'd like to encourage as much as possible along the way, as long as we aren't introducing significant functional changes. Of course if the team disagrees with how the refactoring was done then I would expect reviewers to say so. If we universally agreed with didn't want it the way it is, for example, I'd certainly go revert a few commits and rework it.

**Comment by pchristopher1275** [comment]
I don’t think that the problem is with the diff as being hard to process. The problem, as I see it, is that the ticket was described, discussed, and prioritized based on the text of the ticket. But the actual work that was done was in excess of that requested. And this extra work reverberates in terms of how long it takes developers to digest the patch, how long it takes developers to merge the patch with their existing code, etc. But no one discussed these extra costs, and priority couldn’t have been properly assigned to the ticket as a result — because no one had an accurate picture of what was going to be done. 

Does it mean the work needs to be undone/rejected? I wouldn’t necessarily argue that. But, 
we can’t have an accurate process, if we don’t have good correspondence between tickets-issued, and tickets-implemented. It seems to me that we need to acknowledge that the matchup of those two things for this patch isn’t great: and that future patches would be better to stick closer to the script.

**Comment by cgilling** [comment]
Perhaps this is a discussion we can defer to the sprint retrospective?

**Comment by dankinder** [comment]
Sure. FYI I have already been working on the pull request that builds on this one and it too has some refactoring, but yes maybe this is better discussed in a retrospective.

Any other feedback on this one?

**Comment by fitzboy** [comment]
my two cents: I want to encourage good developers to do good refactoring, and to minimize the amount of time in "process" related stuff... In this case, I think that the appropriate amount of communication would be that when Dan realized that he should refactor that code, he should have done a 5 minute video chat with people that he knows are also working on the same part of the code, to let them know and see if that causes problems... but then go ahead and do it after that... 

Pete mentioned " And this extra work reverberates in terms of how long it takes developers to digest the patch, how long it takes developers to merge the patch with their existing code, etc." --> this suggests that it took you time to digest the change made. So, doing the git pull and fixing conflicts took a long time? Or just reading the diff/changes and understanding it took a long time? well, in either case, I would still vote to say that a refactor that makes sense should always get done, else you find yourself with a load of tech-debt later on...

**Comment by pchristopher1275** [comment]
Refactoring should always be done to improve code quality, no disagreement. But refactoring should be done within the context of the system that management asked us to work in, no(?). In terms of the process overhead, I'm sure we all agree that the less protocol, the better. But we meet every morning at 9am, that seems like a good time to let folks know that the scope of the ticket needs to be expanded, and why.

**Comment by fitzboy** [comment]
Agreed. takeaway: 1) refactor wherever you can and it makes sense 2) socialize that you are refactoring via announcing it to people at standup 3) do NOT get bogged down in process/overhead

**Comment by dankinder** [comment]
I personally wouldn't consider this a scope increase, since I do expect maintenance refactoring to be a basic part of implementing features.

However I respect that you'd like to make these things as visible as possible, that makes sense. I think when we look at tickets we can do our best to predict potential refactoring and also call it out when we think we need to do it. I will do my best to do that.

**Comment by cgilling** [comment]
I would say there are two types of refactoring:

1. Refactoring that is directly related to the code you are working on, doesn't affect a large amount of the code base, and can be done relatively quickly
2. Other refactors that are larger/wider in reach/scope or are known to affect something someone else working on in the sprint.

I would guess this refactor took about an hour max which in my opinion doesn't increase the scope of the ticket (it was estimated as small not extra small). Also this is the kind of thing that we want to encourage as we go. I can see that these methods worked fine the way they were and there weren't many of them so having them as individual methods was fine. But at some point, it makes more sense to do what Dan did in this refactor, and that is just part of implementing a new feature. This is one of the things that the C++ TDD book that we've circulated around the team talks about. One should always be doing these small refactors as new features are implemented. In my opinion its just part of what development is.

That said, I think is good to socialize at stand up (either saying I'm going to do this, or I did this, does anyone see a problem with that) so that if someone else is going to work on that code soon they know to wait for the branch to be merged in.

**Comment by pchristopher1275** [comment]
Ok, thanks guys. I feel better about where we are on this. AFAIC I think this patch is good :+1:

**Pull request merged**
