### PR TITLE
Trn 606 dispatch one shot

### PR DESCRIPTION
**Pull request by pchristopher1275**
We have ongoing issues with timed tests in the dispatcher (and fetcher, and other) test code. These issues manifest as tests reporting false negatives, that are corrected with rerun. The problem is particularly noticeable on the travis system, which runs slower than our cpod machines, and hence more likely time-limits a test. This patch will add a oneShot method to the dispatcher, which will synchronously run the dispatcher until all the available links are dispatched, and then return. With one shot we can replace test code that looks like this

### CODE REVIEW

**Comment by pchristopher1275** [comment]
Was able to remove all but one timed test. Built auto-retry into the one timed test.

**Comment by cgilling** [comment]
Just for informations sake, did this speed up running the tests at all?

**Comment by pchristopher1275** [comment]
Yea the performance improvement is measurable. Shaved 3-4 seconds off the run time of the cassandra tests (new results for 3 runs: 29s, 29s, 30s. old results for 3 runs 33s, 33s, 34s). The total run time of the tests includes both the datastore tests (which weren't spead up), and the dispatcher tests (which were sped up). But even with this oversampled batch, we see a 10% improvement in performance, along with predictable test runs.

**Comment by cgilling** [comment]
great, do you think there are similar things we can do with the datastore, or those just take a long time because its interacting with cassandra?

**Comment by pchristopher1275** [comment]
The trick we're using here won't speed up datastore tests much -- so the net slowness has to do with interfacing with cassandra. But it will speed up the fetcher tests, possibly more significantly.

**Comment by dankinder** [comment]
Code looks fine to me :facepunch:

**Pull request merged**
