### PR TITLE
dispatcher: change log levels slightly

### PR DESCRIPTION
**Pull request by dankinder**
Realized when running live that a bit of the recent dispatcher logging
is too spammy for DEBUG level and should be FINE.

### CODE REVIEW

**Comment by cgilling** [comment]
There's no way to just not execute that code depending on log level is there?

**Comment by dankinder** [comment]
I had initially checked and it seemed there was no way.

Then it occurred to me that I could just create a little closure with a `String()` method.

Then, even better, I found that `log4go.Logc` does this.

So the code would look like this:
```
        log4go.Logc(log4go.FINE, func() string {                                             
            out := "List before deduplication:\n"                                            
            for _, link := range l {                                                         
                out += fmt.Sprintf("    %v\n", link.URL)                                     
            }                                                                                
            out += "List after deduplication:\n"                                             
            for _, link := range deduped {                                                   
                out += fmt.Sprintf("    %v\n", link.URL)                                     
            }                                                                                
            return out                                                                       
        })
```

With one big obvious disadvantage: If loglevel is on FINE and we dispatch a site with millions of links, we'll need to allocate this huge string in memory all at once. Any way around this seems to get overly complicated.

Given the memory issue I'm leaning toward the existing implementation but open about it.

**Comment by cgilling** [comment]
I see, I'm starting to understand more why they built [glog](https://github.com/golang/glog)

**Comment by cgilling** [comment]
Good for now :+1:

**Pull request merged**
